name: MetaSanity
channels:
  - anaconda
  - bioconda
  - conda-forge
  - rmg
dependencies:
  - python=3.6
  - pplacer
  - kofamscan
  - hmmer
  - future
  - pip
  - virsorter
  - gtdbtk
  - fasttree
  - Cython
  - pip
  - blast
  - pftools
  - perl
  - glibc
  - perl-bioperl
  - perl-io-string
  - blast
  - blast-legacy
  - pip:
    - matplotlib
    - dendropy
    - drep
    - luigi
    - pandas
    - numpy
    - scipy
    - BioMetaDB==v0.1.3.0
    - KEGGDecoder
    - checkm-genome
    - argparse
    - configparser