language: python
cache:
  directories:
    - "$HOME/.cache/pip"
    - ".tox"

python:
  - "3.6"
  - "3.5"

# 3.7 needs Xenial image because of https://github.com/travis-ci/travis-ci/issues/9069
matrix:
  include:
    - python: "3.7"
      dist: xenial

install:
  - pip install --upgrade pip
  - pip install codecov
  - pip install tox-travis
script: tox
after_success: codecov
